

stages:

  generate_images:
    params:
      - prompt
    cmd: python -m python_coreml_stable_diffusion.pipeline -i models -o data/processed --compute-unit CPU_AND_GPU --seed 193 --prompt '${prompt}'
    deps:
      - models
    outs:
      - data/processed