stages:
  convert_model:
    cmd: python -m python_coreml_stable_diffusion.torch2coreml --convert-unet --convert-text-encoder --convert-vae-decoder --convert-safety-checker -o models 
    outs:
      - models
  generate_images:
    cmd: python -m python_coreml_stable_diffusion.pipeline --prompt "a photo of an astronaut riding a horse on mars" -i models -o data/processed --compute-unit ALL --seed 193
    deps:
      - models
    outs:
      - data/processed